<a href="https://colab.research.google.com/github/utsabsarkar12/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
print("Utsab")

Utsab


In [39]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [40]:
## Introduction to tensor

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [41]:
scalar.ndim

0

In [42]:
scalar.item()

7

In [43]:
# Vactor
vactor = torch.tensor([7,7])
vactor

tensor([7, 7])

In [44]:
# Matrix

MATRIX = torch.tensor([[[7, 9],
                       [9, 10],
                       [5, 8]],[[7, 9],
                       [9, 10],
                       [5, 8]]])
MATRIX

tensor([[[ 7,  9],
         [ 9, 10],
         [ 5,  8]],

        [[ 7,  9],
         [ 9, 10],
         [ 5,  8]]])

In [45]:
MATRIX[0]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [46]:
MATRIX[1]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [47]:
MATRIX.shape

torch.Size([2, 3, 2])

### Random Tensors

In [48]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0904, 0.2868, 0.8243, 0.1232],
        [0.9435, 0.4711, 0.3000, 0.9515],
        [0.1786, 0.8650, 0.3858, 0.4140]])

In [49]:
random_tensor.ndim

2

In [50]:
random_tensor.shape

torch.Size([3, 4])

In [51]:
## create a random tensor with similar shape to an image tensor
## color channel, height, width
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)