<a href="https://colab.research.google.com/github/utsabsarkar12/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Utsab")

Utsab


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [3]:
## Introduction to tensor

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vactor
vactor = torch.tensor([7,7])
vactor

tensor([7, 7])

In [7]:
# Matrix

MATRIX = torch.tensor([[[7, 9],
                       [9, 10],
                       [5, 8]],[[7, 9],
                       [9, 10],
                       [5, 8]]])
MATRIX

tensor([[[ 7,  9],
         [ 9, 10],
         [ 5,  8]],

        [[ 7,  9],
         [ 9, 10],
         [ 5,  8]]])

In [8]:
MATRIX[0]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [9]:
MATRIX[1]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [10]:
MATRIX.shape

torch.Size([2, 3, 2])

### Random Tensors

In [11]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4340, 0.5007, 0.0534, 0.8914],
        [0.3135, 0.6470, 0.8388, 0.6278],
        [0.9697, 0.7273, 0.3682, 0.7702]])

In [12]:
random_tensor.ndim

2

In [13]:
random_tensor.shape

torch.Size([3, 4])

In [14]:
## create a random tensor with similar shape to an image tensor
## color channel, height, width
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [15]:
## Float 32 tensoor
float_32_tensor = torch.tensor([33.0, 66.0, 99.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([33., 66., 99.])

In [16]:
float_32_tensor.dtype

torch.float32

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([33., 66., 99.], dtype=torch.float16)

In [18]:
float_16_tensor* float_32_tensor

tensor([1089., 4356., 9801.])

In [19]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [20]:
float_32_tensor*int_32_tensor

tensor([ 99., 396., 891.])