<a href="https://colab.research.google.com/github/utsabsarkar12/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to tensor

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vactor
vactor = torch.tensor([7,7])
vactor

tensor([7, 7])

In [6]:
# Matrix

MATRIX = torch.tensor([[[7, 9],
                       [9, 10],
                       [5, 8]],[[7, 9],
                       [9, 10],
                       [5, 8]]])
MATRIX

tensor([[[ 7,  9],
         [ 9, 10],
         [ 5,  8]],

        [[ 7,  9],
         [ 9, 10],
         [ 5,  8]]])

In [7]:
MATRIX[0]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [8]:
MATRIX[1]

tensor([[ 7,  9],
        [ 9, 10],
        [ 5,  8]])

In [9]:
MATRIX.shape

torch.Size([2, 3, 2])

### Random Tensors

In [10]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6466, 0.2707, 0.2060, 0.8247],
        [0.6759, 0.7561, 0.9230, 0.9616],
        [0.4121, 0.9522, 0.5323, 0.6302]])

In [11]:
random_tensor.ndim

2

In [12]:
random_tensor.shape

torch.Size([3, 4])

In [13]:
## create a random tensor with similar shape to an image tensor
## color channel, height, width
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [14]:
## Float 32 tensoor
float_32_tensor = torch.tensor([33.0, 66.0, 99.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([33., 66., 99.])

In [15]:
float_32_tensor.dtype

torch.float32

In [16]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([33., 66., 99.], dtype=torch.float16)

In [17]:
float_16_tensor* float_32_tensor

tensor([1089., 4356., 9801.])

In [18]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [19]:
float_32_tensor*int_32_tensor

tensor([ 99., 396., 891.])

In [20]:
## Getting informatioon from tensor

#create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0736, 0.4977, 0.5330, 0.2700],
        [0.5124, 0.7960, 0.4996, 0.9474],
        [0.4848, 0.2069, 0.5174, 0.1277]])

In [21]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0736, 0.4977, 0.5330, 0.2700],
        [0.5124, 0.7960, 0.4996, 0.9474],
        [0.4848, 0.2069, 0.5174, 0.1277]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [22]:
## Manipulating Tensor (tensor operation)

# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [23]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [24]:
# Matrix Multiplication by element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [25]:
torch.matmul(tensor, tensor)

tensor(14)

In [26]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                          [9,10],
                          [11,12]])

In [27]:
## Here tensor_a and tensor_b has different shape that cann't multyply. so we need to transpose it.

tensor_B.T,

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),)

In [28]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [29]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
# find the mean of x
x = x.type(torch.float32)
x.mean()

tensor(45.)

In [31]:
x
x.shape

torch.Size([10])

In [32]:
# Add an extra dimension
x_reshape = x.reshape(2,5)
x_reshape

tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]])

## Indexing (selecting data from tensor)


In [33]:
# Create a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [34]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
x[0][0]

tensor([1, 2, 3])

In [36]:
x[0][0][1]

tensor(2)

# Pytorch tensors & Numpy


In [38]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1, 2, 3]))

In [39]:
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [40]:
array.dtype

dtype('float64')

In [41]:
## 3.42